### PR TITLE
fixes #238 -- attempt to do a basic clusterfuzzlite integration

### LINKED ISSUE #238: Consider setting up clusterfuzzlite
https://security.googleblog.com/2021/11/clusterfuzzlite-continuous-fuzzing-for.html

This may be better than the ad-hoc fuzzing we do in CI.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
@jonathanmetzman your prompting yesterday got me to finally start looking at this. is there anything we ought to know in terms of ways to speed up the build itself? (pulling the container is 45 seconds, which for a small-ish package like this is 😬)

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman your prompting yesterday got me to finally start looking at this. is there anything we ought to know in terms of ways to speed up the build itself? (pulling the container is 45 seconds, which for a small-ish package like this is grimacing)

Thanks for trying this. I don't really know how I can speed this up especially the pull (other than slimming down the oss-fuzz builders which I've spent a lot of time on already, so probably not a lot of gains there)

**Comment by jonathanmetzman** [comment]
Let me try to look again tomorrow

**Comment by jonathanmetzman** [comment]
> Let me try to look again tomorrow

The best thing I can think of is something that allows devs to build fuzzers in the way they choose (ie without using our image to build it) but we have avoided implementing this so things "just work" more often

**Comment by alex** [comment]
Yes, the "just working" of this is nice :-)

**Comment by alex** [comment]
See https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/ for full docs

I think this is now the minimal implementation that's ready for review. The major things I skipped:

- separate corpus repo (because $effort, but also because I hate setting up PATs for things like this)
- corpus pruning and coverage jobs

**Comment by alex** [comment]
@jonathanmetzman one suggestion: Would it make sense to package stuff as reusable workflows (https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) rather than as reusable actions?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman one suggestion: Would it make sense to package stuff as reusable workflows (https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) rather than as reusable actions?

I think it does make sense. I haven't had a chance to try this due to travel but it is on my radar: https://github.com/google/clusterfuzzlite/issues/101
I'm going to look into next week.

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
